# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      #  See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples

deploy-job:
  docker:
    - image: my-image-version-tag
  working_directory: /tmp/my-project
  steps:
    - run:
        name: Deploy Master to GKE
        command: ./deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
         requires:
           - build-job
         filters:
           branches:
             only: master



