# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.0
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#     - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
          destination: test-results
      #  See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
deploy-job:
  docker:
    - image: google/cloud-sdk
  working_directory: /tmp/my-project
  steps:
    - run:
        name: Deploy Master to GKE
        command: ./deploy.sh
deployment:
  production:
    branch: master
    commands:
      - ./gradlew publishApkRelease
      - Dorg.gradle.project.track=production
  beta:
    branch: develop
    commands:
      - ./gradlew publishApkRelease
      - Dorg.gradle.project.track=beta


